version: 2.1

executors:
  machine-config:
    docker:
      - image: circleci/node:12.16.3

jobs:
  test:
    executor: machine-config
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install

  deploy:
    executor: machine-config
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm install for functions
          command: |
            cd functions
            npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
