version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.16.3
    working_directory: ~/circleci-workflows
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm install for functions
          command: |
            cd functions
            npm install
      - run:
          name: build
          command: npm run build
      - save_cache:
          key: repo-dist
          paths:
            - ~/circleci-workflows
  deploy:
    machine:
      enabled: true
    steps:
      - restore_cache:
          keys:
            - repo-dist
      - run:
          name: install firebase-tools
          command: sudo npm install firebase-tools -g
      - run:
          name: deploy to Firebase Hosting
          command: firebase deploy --token=$FIREBASE_TOKEN

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
